./Datasets/lines_60hz/calibration_bias/rep1.csv
./Datasets/lines_60hz/calibration_bias/rep8.csv
./Datasets/lines_60hz/calibration_bias/rep9.csv
./Datasets/lines_60hz/calibration_bias/rep5.csv
./Datasets/lines_60hz/calibration_bias/rep4.csv
./Datasets/lines_60hz/calibration_bias/rep2.csv
./Datasets/lines_60hz/calibration_bias/rep3.csv
./Datasets/lines_60hz/calibration_bias/rep0.csv
./Datasets/lines_60hz/calibration_bias/rep6.csv
./Datasets/lines_60hz/calibration_bias/rep7.csv
bias is:[[0.012292178091908279, 0.09783434643278971, -0.01561917035206992], [-1.0158824869345685e-05, -8.085483176263612e-05, 1.2908405249644562e-05]]
 don't remove bias
length before delineation: 121
length after delineation: 9
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 57
length before delineation: 121
length after delineation: 73
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 21
length before delineation: 121
length after delineation: 19
length before delineation: 121
length after delineation: 23
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 31
length before delineation: 121
length after delineation: 31
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 51
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 29
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 31
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 51
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 29
length before delineation: 121
length after delineation: 31
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 31
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 31
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 33
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 97
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 81
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 51
length before delineation: 121
length after delineation: 95
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 55
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 61
length before delineation: 121
length after delineation: 91
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 69
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 61
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 81
length before delineation: 121
length after delineation: 65
length before delineation: 121
length after delineation: 51
length before delineation: 121
length after delineation: 123
length before delineation: 121
length after delineation: 63
length before delineation: 121
length after delineation: 115
length before delineation: 121
length after delineation: 75
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 77
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 55
length before delineation: 121
length after delineation: 57
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 11
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 21
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 29
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 53
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 37
length before delineation: 121
length after delineation: 91
length before delineation: 121
length after delineation: 89
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 59
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 97
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 77
length before delineation: 121
length after delineation: 75
length before delineation: 121
length after delineation: 55
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 45
length before delineation: 121
length after delineation: 77
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 35
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 49
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 41
length before delineation: 121
length after delineation: 93
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 77
length before delineation: 121
length after delineation: 91
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 39
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 81
length before delineation: 121
length after delineation: 47
length before delineation: 121
length after delineation: 89
length before delineation: 121
length after delineation: 43
length before delineation: 121
length after delineation: 37
length before delineation: 181
length after delineation: 135
length before delineation: 181
length after delineation: 149
length before delineation: 181
length after delineation: 141
length before delineation: 181
length after delineation: 123
length before delineation: 181
length after delineation: 125
length before delineation: 181
length after delineation: 131
length before delineation: 181
length after delineation: 141
length before delineation: 181
length after delineation: 141
length before delineation: 181
length after delineation: 133
length before delineation: 181
length after delineation: 131
length before delineation: 181
length after delineation: 119
length before delineation: 181
length after delineation: 127
length before delineation: 181
length after delineation: 133
length before delineation: 181
length after delineation: 125
length before delineation: 181
length after delineation: 133
length before delineation: 181
length after delineation: 127
length before delineation: 181
length after delineation: 139
length before delineation: 181
length after delineation: 143
length before delineation: 181
length after delineation: 143
length before delineation: 181
length after delineation: 131
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 111
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 117
length before delineation: 181
length after delineation: 121
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 129
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 111
length before delineation: 181
length after delineation: 117
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 119
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 119
length before delineation: 181
length after delineation: 123
length before delineation: 181
length after delineation: 109
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 97
length before delineation: 181
length after delineation: 101
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 109
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 121
length before delineation: 181
length after delineation: 119
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 109
length before delineation: 181
length after delineation: 145
length before delineation: 181
length after delineation: 115
length before delineation: 181
length after delineation: 119
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 111
length before delineation: 181
length after delineation: 123
length before delineation: 181
length after delineation: 125
length before delineation: 181
length after delineation: 117
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 121
length before delineation: 181
length after delineation: 129
length before delineation: 181
length after delineation: 109
length before delineation: 181
length after delineation: 113
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 117
length before delineation: 181
length after delineation: 133
length before delineation: 181
length after delineation: 129
length before delineation: 181
length after delineation: 133
length before delineation: 181
length after delineation: 131
length before delineation: 181
length after delineation: 123
length before delineation: 181
length after delineation: 127
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 91
length before delineation: 181
length after delineation: 97
length before delineation: 181
length after delineation: 95
length before delineation: 181
length after delineation: 97
length before delineation: 181
length after delineation: 97
length before delineation: 181
length after delineation: 99
length before delineation: 181
length after delineation: 97
length before delineation: 181
length after delineation: 95
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 95
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 107
length before delineation: 181
length after delineation: 105
length before delineation: 181
length after delineation: 99
length before delineation: 181
length after delineation: 87
length before delineation: 181
length after delineation: 97
length before delineation: 181
length after delineation: 101
length before delineation: 181
length after delineation: 95
length before delineation: 181
length after delineation: 67
length before delineation: 181
length after delineation: 59
length before delineation: 181
length after delineation: 59
length before delineation: 181
length after delineation: 61
length before delineation: 181
length after delineation: 69
length before delineation: 181
length after delineation: 63
length before delineation: 181
length after delineation: 67
length before delineation: 181
length after delineation: 65
length before delineation: 181
length after delineation: 71
length before delineation: 181
length after delineation: 77
length before delineation: 181
length after delineation: 73
length before delineation: 181
length after delineation: 71
length before delineation: 181
length after delineation: 77
length before delineation: 181
length after delineation: 85
length before delineation: 181
length after delineation: 75
length before delineation: 181
length after delineation: 77
length before delineation: 181
length after delineation: 73
length before delineation: 181
length after delineation: 77
length before delineation: 181
length after delineation: 57
length before delineation: 181
length after delineation: 65
14
1
